### ISSUE TITLE
cherry-pick法を使ったときにリリースノートに変更履歴に入ってないPR(現在出ているmergeされてないPR)が入ってしまう

### ISSUE THREAD

**Issue by 0num4** [matsuri-tech/generate-release-notes-body-based-on-pull-requests#176]
リリース内容自体に問題はないです。
ref: https://github.com/matsuri-tech/m2m-core/pull/2408

**Comment by hrdtbs** [comment]
PRを取得する方法から、現在のブランチとデプロイ先の差分からマージコミットを抽出する仕組みに変更すれば出来るかも？
