### ISSUE TITLE
node 12 から、16に上げたい　(お気持ち表明)

### ISSUE THREAD

**Issue by ekusiadadus** [matsuri-tech/generate-release-notes-body-based-on-pull-requests#177]
https://github.com/matsuri-tech/generate-release-notes-body-based-on-pull-requests/blob/264beb91c130de1100f9cbf7c008bca8c3b30607/action.yml#L10

**Comment by hrdtbs** [comment]
:hakusyu: 正しさ。

こういうのもrenovateはバージョン上げてくれるので、このリポジトリもrenovateに移行したいですね。

**Comment by hrdtbs** [comment]
18設定できなさそうですね。
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing

**Comment by ekusiadadus** [comment]
16にします:bow:
